---
title: "Database_connect"
author: "Jakob Skelmose"
date: '2024-01-24'
output: html_document
---
```{r}
library(DBI)

my_oracle <- dbConnect(odbc::odbc(),
                       Driver = "Oracle in instantclient_21_12",
                       DBQ = "localhost:1521/XEPDB1", 
                       UID = "system",
                       PWD = "test1234",
                       trusted_connection = TRUE)

```


```{r}
query <- "SELECT
  sp.MERGED_PATIENT_ID,
  sp.LINK_NUMBER,
  at.PATIENTID,
  at.DIAGNOSISDATEBEST,
  at.SITE_ICD10_O2_3CHAR,
  at.AGE,
  at.SEX,
  at.QUINTILE_2015,
  st.MERGED_TUMOUR_ID,
  st.PRIMARY_DIAGNOSIS,
  sr.CLINICAL_TRIAL,
  sr.HEIGHT_AT_START_OF_REGIMEN,
  sr.WEIGHT_AT_START_OF_REGIMEN
FROM
  ANONYMOUS.SIM_SACT_PATIENT sp
LEFT JOIN
  ANONYMOUS.SIM_AV_TUMOUR at
ON
  sp.LINK_NUMBER = at.LINKNUMBER
LEFT JOIN
  ANONYMOUS.SIM_SACT_TUMOUR st
ON
  sp.MERGED_PATIENT_ID = st.MERGED_PATIENT_ID
LEFT JOIN
  ANONYMOUS.SIM_SACT_REGIMEN sr
ON
  sp.MERGED_PATIENT_ID = sr.MERGED_PATIENT_ID AND st.MERGED_TUMOUR_ID = sr.MERGED_TUMOUR_ID"

```

```{r}
data <- dbGetQuery(my_oracle, query)
```

```{r}
print(data)
```