SELECT
  sp.MERGED_PATIENT_ID,
  sp.LINK_NUMBER as LINKNUMBER,
  at.DIAGNOSISDATEBEST,
  at.SITE_ICD10_O2_3CHAR,
  at.AGE,
  at.SEX,
  at.QUINTILE_2015,
  st.PRIMARY_DIAGNOSIS,
  sr.CLINICAL_TRIAL,
  sr.HEIGHT_AT_START_OF_REGIMEN,
  sr.WEIGHT_AT_START_OF_REGIMEN
FROM
  SIM_SACT_PATIENT sp
LEFT JOIN
  SIM_AV_TUMOUR at
ON
  sp.LINK_NUMBER = at.LINKNUMBER
LEFT JOIN
  SIM_SACT_TUMOUR st
ON
  sp.MERGED_PATIENT_ID = st.MERGED_PATIENT_ID
LEFT JOIN
  SIM_SACT_REGIMEN sr
ON
  sp.MERGED_PATIENT_ID = sr.MERGED_PATIENT_ID AND st.MERGED_TUMOUR_ID = sr.MERGED_TUMOUR_ID
